- name: ensure log folder exists and is writeable
  ansible.builtin.file:
    path: "{{ restic_log_dir }}"
    owner: '{{ restic_user }}'
    group: '{{ restic_user }}'
    mode: '0755'
- name: ensure cache dir exists and is writeable
  ansible.builtin.file:
    path: "{{ restic_log_dir }}"
    owner: '{{ restic_user }}'
    group: '{{ restic_user }}'
    mode: '0750'
- name: Set ownership recursively
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    recurse: true
  with_items:
  - "{{ restic_log_dir }}"
  - "{{ restic_cache_dir }}"
